export const BASE_URL="http://localhost:5001/"
export const USERS_URL = 'api/users';
export const PRODUCTS_URL ="api/products"
export const STORES_URL="api/stores"
export const DOCUMENTS_URL="api/documents"
export const CATEGORY_URL="api/categories"
export const AVAILABLE_STORES_URL="api/stores/availableStores"
export const COMPANIES_URL="api/companies"
export const CREDITS_URL ="api/credits"
export const BRANDS_URL="api/brands"
export const STATS_URL="api/stats"
export const STORE_MANAGER="STORE_MANAGER"
export const STORE_EMPLOYEE="STORE_EMPLOYEE"
export const BANK_AGENT="BANK_AGENT"
export const ADMIN="ADMIN"
export const APP_ID='236167247f47d433'
export const REGION='eu'
export const AUTH_KEY='7906b23ffdf3750dfff6f477cb74253cd1b50fcc'